name: Docker Production
on:
  push:
    branches:
      - master
env:
  VERSION: $(node -e "console.log(require('./package.json').version)")
  IMAGE_NAME: deadeokdevelopergroup/match-making-server
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Authenticating Docker repositry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: Tag Docker Image with Latest
        run: docker tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} ${{ env.IMAGE_NAME }}:latest
      - name: Push Docker Image tagged Latest
        run: docker push ${{ env.IMAGE_NAME }}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 'kr.slowmotion.dev'
          app-name: 'thikira'
          git-push-flags: '--force'
